# If you see me, please update my `rev` field using the provided links
# Click the repo and update to latest tags.
# If things break on update, raise an issue
repos:

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort imports autosklearn
        files: autosklearn/.*

      - id: isort
        name: isort imports test
        files: test/.*

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: black formatter autosklearn
        files: autosklearn/.*

      - id: black
        name: black formatter test
        files: test/.*

      - id: black
        name: black formatter examples
        files: examples/.*

  # This is disabled as most modules fail this
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        files: DISABLED # autosklearn/.*
        always_run: false
        additional_dependencies: ["toml"] # Needed to parse pyproject.toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        name: mypy auto-sklearn
        files: autosklearn/.*

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: flake8 autosklearn
        files: autosklearn/.*

      - id: flake8
        name: flake8 test
        files: test/.*
