name: black-format-check

on: [push, pull_request]

env:
  #If STRICT is set to true, it will fail on black check fail
  STRICT: false

jobs:

  black-format-check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install black
      run: |
        pip install black

    - name: Run Black Check
      run: |
        black --check --diff --line-length 100 ./autosklearn || ! $STRICT
        black --check --diff --line-length 100 ./test || ! $STRICT
        black --check --diff --line-length 100 ./examples|| ! $STRICT
